import { meta, 
    shopify, 
    starbucks, 
    sisenex, 
    kaseya,
    dhauz_logo,
    adapta_logo,
    tesla, 
    image, 
    logo,
    presentedigital1,
    presentedigital2,
    presentedigital3,
    presentedigital4,
    presentedigital5,
    presentedigital6,
    presentedigital7,
    zapstter1,
    zapstter2,
    zapstter3,
    zapstter4,
    zapstter5,
    zapstter6,
    zapstter7,
    imagegit1,
    imagegit2,
    snake1,
    snake2,
    ui1,
    ui2,
    ui3,
    ui4,
    ui5,
    face1,
    face2,
    face3,
    face4,
    face5,
    sleep1,
    sleep2,
    sleep3,
    mdsocial,
    panda1,
    panda2,
    amazon,
    amazon2,
    amazon3,
    cognisense1,
    cognisense2,
    cognisense3,
    cognisense4,
    hangmans1,
    hangmans2,
    hangmans3,
    hangmans4,
    jobcandidates1,
    jobcandidates2,
    jobcandidates3,
    jobcandidates4,
    jobcandidates5,
    jobcandidates6,
    jobcandidates7,
    jobcandidates8,
    lifemap1,
    lifemap2,
    lifemap3,
    lifemap4,
    rag1,
    rag2,
    rag3,
    rag4,
    rag5,
    rag6,
    rag7,
    rag8,
    rag9,
} from "../assets/images";

import {
    car,
    contact,
    css,
    estate,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    mui,
    nextjs,
    nodejs,
    pricewise,
    react,
    redux,
    sass,
    snapgram,
    summiz,
    tailwindcss,
    threads,
    typescript,
    bootstrap,
    vuejs,
    aws,
    googlecloud,
    restapi,
    figma,
    mysql,
    postgresql,
    docker,
    jira,
    python,
    postman,
    jquery,
    linux,
} from "../assets/icons";

export const skills = [
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Language",
    },
    {
        imageUrl: nextjs,
        name: "Next.js",
        type: "Frontend",
    },
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: python,
        name: "Python",
        type: "Language",
    },
    {
        imageUrl: postgresql,
        name: "PostgreSQL",
        type: "Database",
    },
    {
        imageUrl: docker,
        name: "Docker",
        type: "DevOps",
    },
    {
        imageUrl: aws,
        name: "AWS",
        type: "Cloud",
    },
    {
        imageUrl: googlecloud,
        name: "Google Cloud",
        type: "Cloud",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: restapi,
        name: "REST API",
        type: "Backend",
    },
    {
        imageUrl: mysql,
        name: "MySQL",
        type: "Database",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Language",
    },
    {
        imageUrl: express,
        name: "Express",
        type: "Backend",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    {
        imageUrl: html,
        name: "HTML",
        type: "Frontend",
    },
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: postman,
        name: "Postman",
        type: "Tools",
    },
    {
        imageUrl: linux,
        name: "Linux",
        type: "Tools",
    },
    {
        imageUrl: jira,
        name: "Jira",
        type: "Tools",
    },
    {
        imageUrl: figma,
        name: "Figma",
        type: "Design",
    },
    {
        imageUrl: bootstrap,
        name: "Bootstrap",
        type: "Frontend",
    },
    {
        imageUrl: sass,
        name: "Sass",
        type: "Frontend",
    },
    {
        imageUrl: redux,
        name: "Redux",
        type: "State Management",
    },
    {
        imageUrl: vuejs,
        name: "Vue.js",
        type: "Frontend",
    },
    {
        imageUrl: jquery,
        name: "jQuery",
        type: "Frontend",
    },
];

export const experiences = [
    {
        title: "Domain Lead",
        company_name: "Adapta",
        icon: adapta_logo,
        iconBg: "#0f0f0f",
        date: "Mar 2026 - Jun 2026",
        points: [
            "Led the technical direction of the platform's core domains: scheduled tasks, skills system, and context management.",
            "Coordinated a team of 2 engineers, owning product decisions, feature prioritization, and architecture definition across those areas.",
            "Resolved critical infrastructure challenges including timeout handling and server-to-server authentication on the scheduled tasks domain.",
            "Led a major refactor of the application's core logic to operate asynchronously via scheduled tasks, enabling reliable async processing of the platform's most critical LLM-based workflows.",
            "Served as the primary technical reference and PR reviewer for all work within these domains.",
        ],
    },
    {
        title: "Senior Software Engineer",
        company_name: "Adapta",
        icon: adapta_logo,
        iconBg: "#0f0f0f",
        date: "Sep 2025 - Mar 2026",
        points: [
            "Owned the full development lifecycle at one of Latin America's largest AI companies.",
            "Built user interfaces with React and Next.js, developed APIs with Node.js, and managed CI/CD pipelines, automated testing, and data security.",
            "Developed user feedback services from scratch and implemented the payment gateway responsible for the platform's subscription renewals.",
            "Drove LLM performance optimization and cost reduction in production, improving inference reliability and reducing operational costs.",
        ],
    },
    {
        title: "Senior Full-Stack Developer",
        company_name: "Dhauz",
        icon: dhauz_logo,
        iconBg: "#FFF",
        date: "Apr 2025 - Sep 2025",
        points: [
            "Served as tech lead, responsible for defining solution architectures and managing multiple projects across clients.",
            "Worked across Next.js, React, Supabase, Docker, C#, and Angular based on project requirements.",
            "Led integration and ingestion of large volumes of data from Databricks, designing data modeling and consumption strategies.",
            "Implemented CI/CD pipelines using GitHub Workflows to enhance automation and reliability.",
        ],
    },
    {
        title: "Full-Stack Developer",
        company_name: "Dhauz",
        icon: dhauz_logo,
        iconBg: "#FFF",
        date: "Mar 2022 - Apr 2025",
        points: [
            "Grew from intern to mid-level developer building full-stack web applications across multiple client projects.",
            "Built user interfaces and backend services using C#, Angular, Next.js, React, MySQL, Docker, and AWS.",
            "Implemented CRUD operations, API integrations, socket communication, middleware, file handling, and data visualizations.",
            "Managed cloud infrastructure on AWS and delivered scalable, performance-oriented solutions across multiple client projects.",
        ],
    },
    {
        title: "Mobile Developer",
        company_name: "LUMO",
        icon: sisenex,
        iconBg: "#accbe1",
        date: "Jun 2021 - Jun 2022",
        points: [
            "Implemented user-friendly interfaces for evaluators and room monitors on the SisEnex platform.",
            "Developed new screens and functionalities for dynamic interactions during university event presentations.",
            "Integrated GraphQL and RESTful APIs to ensure seamless data synchronization across backend services.",
            "Applied LGPD practices for data privacy compliance and improved application stability through debugging and optimization.",
        ],
    },
];

export const socialLinks = [
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/Gabriel-Alexandre',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/gabrielcarvalho-ia/',
    }
];

export const projects = [
    {
        iconUrl: threads,
        img: [presentedigital1, presentedigital2, presentedigital3, presentedigital4, presentedigital5, presentedigital6, presentedigital7],
        theme: 'btn-back-orange',
        name: 'Virtual Gift',
        description: 'Built a full-stack SaaS platform that allows users to create personalized digital gifts — with photos, videos, custom messages, and animated visual effects — and share them via link or physical QR Code card. The platform handles authentication, subscription plans, and payment processing, and serves over 100 active paying users in production. Features include a multi-step gift builder, 15+ themed templates, animations (hearts, confetti, stars), PDF generation with QR Code, and a freemium pricing model with three tiers.',
        link: 'https://virtual-gift.app/',
    },
    {
        iconUrl: estate,
        img: [zapstter1, zapstter2, zapstter3, zapstter4, zapstter5, zapstter6, zapstter7],
        theme: 'btn-back-green',
        name: 'Zapstter',
        description: 'Built a legal intelligence SaaS platform for tax law firms in Brazil, designed to automate lead generation by monitoring public and private databases in real time. The platform detects fiscal events — open tax executions, cancelled payment plans, active debt inclusion — and delivers qualified leads with decision-maker contact details directly to lawyers\' pipelines. Features include a multi-layer intelligence engine (Legal Signals™, Decision Graph™, Lead Intelligence™, Prospecting Pipeline™), a dynamic pricing calculator, CRM-style lead funnel, and a WhatsApp automation add-on. Built with Next.js 16, TypeScript, React 19, Supabase, and Tailwind CSS.',
        link: 'https://www.zapstter.com/',
    },
    {
        iconUrl: pricewise,
        img: [cognisense1,cognisense2,cognisense3,cognisense4],
        theme: 'btn-back-red',
        name: 'CogniSense',
        description: 'Developed a comprehensive AI insights platform using Next.js, React, and Tailwind CSS for modern web development. The platform offers valuable content about AI advancements with a no-nonsense approach. Features include technical accuracy verification, forward-thinking perspectives, and reader-first content design. The platform helps users navigate the complex AI landscape with confidence, bridging the gap between advanced AI technologies and practical understanding.',
        link: 'https://cognisense.gaxtech.org/',
    },
    {
        iconUrl: pricewise,
        img: [hangmans1,hangmans2,hangmans3,hangmans4],
        theme: 'btn-back-red',
        name: 'Hangmans Tale',
        description: 'Developed a visually stunning hangman game with React and Tailwind CSS, creating an intuitive gaming experience. Players can test their vocabulary and quick thinking with an extensive word collection. Features include custom word sets that allow users to challenge friends and share gameplay sessions. The beautiful design using Next.js enhances user engagement while providing a classic word-guessing adventure in a modern, interactive format.',
        link: 'https://hangmanstale.gaxtech.org/',
    },
    {
        iconUrl: pricewise,
        img: [jobcandidates1,jobcandidates2,jobcandidates3,jobcandidates4,jobcandidates5,jobcandidates6,jobcandidates7,jobcandidates8],
        theme: 'btn-back-red',
        name: 'JobConnect',
        description: 'Developed a comprehensive job search platform connecting job seekers with employers using Next.js, React, and Tailwind CSS. Features include user authentication, job posting and application system, candidate filtering, and profile management. Enhanced user experience with an intuitive interface leveraging Tailwind CSS components. The platform offers thousands of job listings, streamlined application process for job seekers, and advanced candidate filtering tools for employers, while also supporting remote work opportunities.',
        link: 'https://jobcandidates.gaxtech.org/marketing',
    },
    {
        iconUrl: estate,
        img: [amazon,amazon2,amazon3],
        theme: 'btn-back-black',
        name: 'Amazon Clone',
        description: 'Developed a responsive e-commerce application inspired by Amazon using HTML, CSS, and JavaScript, featuring product listings, search functionality, and a user-friendly shopping cart experience.',
        link: 'https://javascript-amazon-project-phi.vercel.app/index.html',
    },
    {
        iconUrl: summiz,
        img: [snake1,snake2],
        theme: 'btn-back-yellow',
        name: 'Snake Game',
        description: 'The Snake Game is a classic arcade game recreated using modern web technologies. This project showcases your ability to implement game logic and create an engaging user interface using HTML, CSS, and JavaScript.',
        link: 'https://snake-game-olive-five.vercel.app/',
    },
    {
        iconUrl: summiz,
        img: [ui1,ui2,ui3,ui4,ui5],
        theme: 'btn-back-yellow',
        name: 'Landing Page - UI/UX Design',
        description: 'The Travel Website is a beautifully designed and highly responsive web application created to inspire and assist travelers.',
        link: 'https://uiux-tawny.vercel.app/',
    }
];